# Setup
title: Arthur Leung
tagline: ""
url: https://aleungplants.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-N1MLN76DPX

# Specify the author for blog posts
author:
  name: Arthur Leung
  url: https://twitter.com/aleungplants
  # email: markdotto@gmail.com

# Nav variable
nav:
  - title: Home
    url: /
  - title: Blog
    url: /archive
